import { TColor } from '../types/Common';

export const GRID_WIDTH = 6;
export const GRID_HEIGHT = 9;

export const ANIMATION_TIME = 300;

export const allColors: TColor[] = ['red', 'yellow', 'orange', 'purple', 'limegreen', 'green', 'blue', 'darkblue'];
export const avatarValues = {
	Top: [
		'NoHair',
		'Eyepatch',
		'Hat',
		'Hijab',
		'Turban',
		'WinterHat1',
		'WinterHat2',
		'WinterHat3',
		'WinterHat4',
		'LongHairBigHair',
		'LongHairBob',
		'LongHairBun',
		'LongHairCurly',
		'LongHairCurvy',
		'LongHairDreads',
		'LongHairFrida',
		'LongHairFro',
		'LongHairFroBand',
		'LongHairNotTooLong',
		'LongHairShavedSides',
		'LongHairMiaWallace',
		'LongHairStraight',
		'LongHairStraight2',
		'LongHairStraightStrand',
		'ShortHairDreads01',
		'ShortHairDreads02',
		'ShortHairFrizzle',
	],
	Accessories: ['Blank', 'Kurt', 'Prescription01', 'Prescription02', 'Round', 'Sunglasses', 'Wayfarers'],
	'Hair Color': [
		'Auburn',
		'Black',
		'Blonde',
		'BlondeGolden',
		'Brown',
		'BrownDark',
		'PastelPink',
		'Blue',
		'Platinum',
		'Red',
		'SilverGray',
	],
	'Facial Hair': ['Blank', 'BeardMedium', 'BeardLight', 'BeardMajestic', 'MoustacheFancy', 'MoustacheMagnum'],
	'Facial Hair Color': ['Auburn', 'Black', 'Blonde', 'BlondeGolden', 'Brown', 'BrownDark', 'Platinum', 'Red'],
	Clothes: [
		'BlazerShirt',
		'BlazerSweater',
		'CollarSweater',
		'GraphicShirt',
		'Hoodie',
		'Overall',
		'ShirtCrewNeck',
		'ShirtScoopNeck',
		'ShirtVNeck',
	],
	'Fabric Color': [
		'Black',
		'Blue01',
		'Blue02',
		'Blue03',
		'Gray01',
		'Gray02',
		'Heather',
		'PastelBlue',
		'PastelGreen',
		'PastelOrange',
		'PastelRed',
		'PastelYellow',
		'Pink',
		'Red',
		'White',
	],
	Eyes: ['Close', 'Cry', 'Default', 'Dizzy', 'EyeRoll', 'Happy', 'Hearts', 'Side', 'Squint', 'Surprised', 'Wink', 'WinkWacky'],
	Eyebrow: [
		'Angry',
		'AngryNatural',
		'Default',
		'DefaultNatural',
		'FlatNatural',
		'RaisedExcited',
		'RaisedExcitedNatural',
		'SadConcerned',
		'SadConcernedNatural',
		'UnibrowNatural',
		'UpDown',
		'UpDownNatural',
	],
	Mouth: [
		'Concerned',
		'Default',
		'Disbelief',
		'Eating',
		'Grimace',
		'Sad',
		'ScreamOpen',
		'Serious',
		'Smile',
		'Tongue',
		'Twinkle',
		'Vomit',
	],
	Skin: ['Tanned', 'Yellow', 'Pale', 'Light', 'Brown', 'DarkBrown', 'Black'],
};

// Dummy Data for FE
export const lobbyMembers = [
	{
		name: 'Ravik',
		color: 'red',
		avatar: {
			Top: 1,
			Accessories: 1,
			'Hair Color': 0,
			'Facial Hair': 0,
			'Facial Hair Color': 1,
			Clothes: 1,
			'Fabric Color': 2,
			Eyes: 1,
			Eyebrow: 1,
			Mouth: 0,
			Skin: 0,
		},
	},
	{
		name: 'Pranab',
		color: 'green',
		avatar: {
			Top: 3,
			Accessories: 2,
			'Hair Color': 1,
			'Facial Hair': 1,
			'Facial Hair Color': 0,
			Clothes: 0,
			'Fabric Color': 1,
			Eyes: 2,
			Eyebrow: 2,
			Mouth: 1,
			Skin: 3,
		},
	},
	{
		name: 'Anish',
		color: 'limegreen',
		avatar: {
			Top: 1,
			Accessories: 1,
			'Hair Color': 0,
			'Facial Hair': 0,
			'Facial Hair Color': 1,
			Clothes: 1,
			'Fabric Color': 2,
			Eyes: 1,
			Eyebrow: 1,
			Mouth: 0,
			Skin: 0,
		},
	},
	{
		name: 'Anish',
		color: 'orange',
		avatar: {
			Top: 1,
			Accessories: 1,
			'Hair Color': 0,
			'Facial Hair': 0,
			'Facial Hair Color': 1,
			Clothes: 1,
			'Fabric Color': 2,
			Eyes: 1,
			Eyebrow: 1,
			Mouth: 0,
			Skin: 0,
		},
	},
	{
		name: 'Anish',
		color: 'blue',
		avatar: {
			Top: 1,
			Accessories: 1,
			'Hair Color': 0,
			'Facial Hair': 0,
			'Facial Hair Color': 1,
			Clothes: 1,
			'Fabric Color': 2,
			Eyes: 1,
			Eyebrow: 1,
			Mouth: 0,
			Skin: 0,
		},
	},
];
