export const GRID_WIDTH = 6;
export const GRID_HEIGHT = 9;

export const ANIMATION_TIME = 300;

export const avatarValues = {
	Top: [
		'NoHair',
		'Eyepatch',
		'Hat',
		'Hijab',
		'Turban',
		'WinterHat1',
		'WinterHat2',
		'WinterHat3',
		'WinterHat4',
		'LongHairBigHair',
		'LongHairBob',
		'LongHairBun',
		'LongHairCurly',
		'LongHairCurvy',
		'LongHairDreads',
		'LongHairFrida',
		'LongHairFro',
		'LongHairFroBand',
		'LongHairNotTooLong',
		'LongHairShavedSides',
		'LongHairMiaWallace',
		'LongHairStraight',
		'LongHairStraight2',
		'LongHairStraightStrand',
		'ShortHairDreads01',
		'ShortHairDreads02',
		'ShortHairFrizzle',
	],
	Accessories: ['Blank', 'Kurt', 'Prescription01', 'Prescription02', 'Round', 'Sunglasses', 'Wayfarers'],
	'Hair Color': [
		'Auburn',
		'Black',
		'Blonde',
		'BlondeGolden',
		'Brown',
		'BrownDark',
		'PastelPink',
		'Blue',
		'Platinum',
		'Red',
		'SilverGray',
	],
	'Facial Hair': ['Blank', 'BeardMedium', 'BeardLight', 'BeardMajestic', 'MoustacheFancy', 'MoustacheMagnum'],
	'Facial Hair Color': ['Auburn', 'Black', 'Blonde', 'BlondeGolden', 'Brown', 'BrownDark', 'Platinum', 'Red'],
	Clothes: [
		'BlazerShirt',
		'BlazerSweater',
		'CollarSweater',
		'GraphicShirt',
		'Hoodie',
		'Overall',
		'ShirtCrewNeck',
		'ShirtScoopNeck',
		'ShirtVNeck',
	],
	'Fabric Color': [
		'Black',
		'Blue01',
		'Blue02',
		'Blue03',
		'Gray01',
		'Gray02',
		'Heather',
		'PastelBlue',
		'PastelGreen',
		'PastelOrange',
		'PastelRed',
		'PastelYellow',
		'Pink',
		'Red',
		'White',
	],
	Eyes: ['Close', 'Cry', 'Default', 'Dizzy', 'EyeRoll', 'Happy', 'Hearts', 'Side', 'Squint', 'Surprised', 'Wink', 'WinkWacky'],
	Eyebrow: [
		'Angry',
		'AngryNatural',
		'Default',
		'DefaultNatural',
		'FlatNatural',
		'RaisedExcited',
		'RaisedExcitedNatural',
		'SadConcerned',
		'SadConcernedNatural',
		'UnibrowNatural',
		'UpDown',
		'UpDownNatural',
	],
	Mouth: [
		'Concerned',
		'Default',
		'Disbelief',
		'Eating',
		'Grimace',
		'Sad',
		'ScreamOpen',
		'Serious',
		'Smile',
		'Tongue',
		'Twinkle',
		'Vomit',
	],
	Skin: ['Tanned', 'Yellow', 'Pale', 'Light', 'Brown', 'DarkBrown', 'Black'],
};
